name: redbiom CI
    
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build-and-run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.6', '3.7', '3.8']
    
    steps:
    - name: Check out repository code
      uses: actions/checkout@v2
      
    - name: Setup for conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true

    - name: Install
      shell: bash -l {0}
      run: |
          conda create --yes -n test-env -c bioconda python=${{ matrix.python-version }} biom-format requests pandas click==6.7 nose sqlite joblib nltk msgpack-python cython "redis<5.0.0"
        conda activate test-env
        conda install -c conda-forge --yes scikit-bio
        pip install flake8 msgpack
        pip install -e . --no-deps 

    - name: Webdis install
      shell: bash -l {0}
      run: |
        sudo apt-get -y install libevent-dev
        git clone https://github.com/nicolasff/webdis
        cd webdis
        make
        pwd

    - name: Test
      shell: bash -l {0}
      run: |
        conda activate test-env
        
        redis-server --daemonize yes
        
        pwd
        pushd webdis
        ./webdis &
        popd
        
        alias md5=md5sum
        export REDBIOM_HOST=http://127.0.0.1:7379
        redbiom summarize contexts  # will return a nonzero exit status if it cannot communicate with the default host
        make test

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: flake8
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: install dependencies
      run: python -m pip install --upgrade pip
    - name: lint
      run: |
        pip install -q flake8
        flake8 --ignore=E731 redbiom
